---
title: "Download data"
author: "steppe"
date: "2023-10-14"
output: html_document
---

```{r}
library(tidyverse)
```

The main bioclim variables can be found at the [link here](https://envicloud.wsl.ch/#/?bucket=https%3A%2F%2Fos.zhdk.cloud.switch.ch%2Fenvicloud%2F&prefix=chelsa%2Fchelsa_V2%2FGLOBAL%2Fclimatologies%2F1981-2010%2Fbio%2F) an S3 bucket for CHELS*A* (not the neighborhood!).
All files can be downloaded as a textfile for further use with wget. 
We will subset these files to only download the layers of interest.

```{r Subset Chelsea bioclim layers}

lyrs2grep <- c('bio1', 'bio4', 'bio5', 'bio6', 'bio10', 'bio11', 'bio12',
               'bio18', 'bio19', # bioclim variables
               'gdd5', 'ngd5', 'gdd10', 'ngd10', # growing degree days
               'gdgfgd5', 'gdgfgd10', # first growing degree day above 5/10 *c
               'tcc_mean', 'vpd_mean', # mean cloud cover, vapour press deficit
               'hurs_mean', # mean monthly near surface humidity
               'scd', # number of days with snow cover
               'swe', # snow water equivalent. 
               'fcf' # number of events where temps go from to/below 0*c
               )
lyrs2grep <- paste0('_', lyrs2grep, '_', collapse = "|") 

bioclim_paths <- read.delim(
  '../data/raw/envidatS3paths-mainbioclim.txt', header = F) %>% 
  rename(Path = V1) %>% 
  filter(str_detect(Path, lyrs2grep))

write.table(bioclim_paths, 
            file = '../data/raw/ClimateVariables.txt', 
            row.names = F ,col.names = F, quote = F)

rm(lyrs2grep, bioclim_paths)
```

```{sh download Chelsa climate variables, eval = F}
URL_LIST=$(<../data/raw/ClimateVariables.txt)
## echo $URL_LIST | xargs -n 1 -P 8 wget -q -P /path/to/folder/
```


```{r download soil grids data eval = F}
library(terra)
library(sf)
library(gdalUtilities)

## download soil grids data

igh = '+proj=igh +lat_0=0 +lon_0=0 +datum=WGS84 +units=m +no_defs' # proj string for Homolosine projection

domain <- rast(nrows = 1, ncols = 1) # create a big empty raster, you can go in through sf too. 
ext(domain) <- c( -125.5, -100, 27,  50) # set the extent
crs(domain) <- "EPSG:4326" # define the projection
domain <- as.polygons(domain) |>  # convert to vector data
  st_as_sf() |> # convert to simple feature
  st_transform(igh) %>% 
  st_bbox()

soilgrids_download <- function(list_vrt, # download url
                               list_lfile, # destination path
                               shape_igh, # AOI shape in IGH proj
                               destproj) { # desired projection
  
  terra::rast(paste0(sg_url, list_vrt)) %>% # read raster
    terra::crop(ext(vect(shape_igh))) %>% # crop to bounding box
    terra::project(destproj) %>% # reproject
    terra::writeRaster(list_lfile,
                       overwrite = T
    ) # @ Tsyplenkov, Anatoly
}

######### Create directory to hold these raw data ###########

if (!dir.exists("soilgrid")) {
  dir.create("soilgrid")
}

# Create paths
lfile <- paste0(
  "soilgrid/",
  props, "_",
  rep(layers, 4),
  ".tif"
)



sg_url = "/vsicurl?max_retry=3&retry_delay=1&list_dir=no&url=https://files.isric.org/soilgrids/latest/data/"

### soil physical-texture properties ###

var <- c('silt', 'clay', 'sand') # these three have all three vars downloaded
depth <- c('0-5', '5-15', '15-30')

vrts <- paste0(var, '/', var, '_', rep(depth, each = length(var)), 'cm_mean.vrt') 

gdal_translate(
  paste0(sg_url, vrts),
               "./crop_roi_igh_r.vrt",
               of = "VRT", tr = c(250, 250),
               projwin = domain,
               projwin_srs = igh)

gdalwarp(source = "./crop_roi_igh_r.vrt",
         destination = "./crop_roi_ll_r.vrt", 
         s_srs = igh, 
         t_srs = "EPSG:5070", 
         of = "VRT",
         overwrite = TRUE)

gdal_translate("./crop_roi_ll_r.vrt",  
               "./crop_roi_ll_r.tif", 
               co=c("TILED=YES", "COMPRESS=DEFLATE", "PREDICTOR=2", "BIGTIFF=YES"))


#### hydroxide content & coarse fragments ####
var <- c('phh2o', 'cfvo')  
depth <- c('0-5', '30-60')


#### soil organic carbon ####
var <- 'soc'  # these only have these depths downloaded
depth <- c('0-5')

#### salinity ####


#### Soil USDA Class ####


```

