---
title: "Generate Random Forest Models"
author: "steppe"
date: "2023-10-14"
output: html_document
---

```{r}
library(tidyverse)
library(terra)
source('functions.R')
```

```{r read in predictors}

p <- '/media/steppe/hdd/Geospatial_data/WesternPlantPredictors2'
paths <- list.dirs(p, recursive = T)
paths <- paths[2:length(paths)]
paths <- paths[! grepl('/chelsa$', paths) ]

# soils need to be uploaded seperately, e.g. by the depths
paths <- paths[! grepl('/soilgrids$', paths) ]

files <- lapply(paths, function(x){ file.path(x, list.files(x)) })
names(files) <- basename(paths)

layers <- lapply(files, vrt)
layers <- rast(layers)
names(layers) <- basename(paths)
plot(layers[[1:3]])

# gdgfgd10", "gdgfgd5, "swe"
# both need NA replaced with 0, if terrestrial... 

layers[[19]] <- subst(layers[[19]], NA, 0)
layers[[19]] <- mask(layers[[19]], layers[[1]]) # remove the ocean/set extent again

plot(layers[[22]])

```

```{r read in response}
p <- '../data/raw/occurrence/combined_records'
p2f <- file.path(p, list.files(p, pattern = '.shp$'))
train_dat <- lapply(p2f, sf::st_read, quiet = TRUE)
train_dat <- bind_rows(train_dat) %>% 
  st_transform(crs(layers))

abvi <- filter(train_dat, taxon == 'Abronia villosa')

abvi_test <- terra::extract(layers, abvi)
```


