---
title: "Introduction"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: pdf_document
---

# Introduction

A primary challenge in effectively restoring Earths terrestrial ecosystems is the lack of available plant germplasm (@national2023assessment, @merritt2011restoration).
Given the scale of our restoration needs, in most scenarios, the only sustainable source of seed is from grow-outs of wild harvested seed in agricultural settings (@pedrini2020collection, @broadhurst2015seeding,  @national2023assessment).
Enormous efforts are now underway to increase the number of species, the number of populations within these species, and the genetic diversity of these populations available for restoration @national2023assessment.
However, difficulties exist in both the wild harvest and increase of seed which are limiting our ability to develop adequate amounts of germplasm material.  
Herein, we identify prospective methods to increase the 1) number of species, 2) populations, and 3) genetic diversity of collections and 4) increase the success of agriculturally produced seed lots using Species Distribution Models and subsequent analysis of them intended to pair them more aptly with species biology and ecology.   

(paragraph about why many species, why locally adapted, reluctant correlation between pop size genetic diversity, why seed needs to be farmed, why decrease the possibility of bottlenecks while farming)


More species per restroation gooood. @wilsey2021restoration
Each collection is generally only cultivated for 1-5 generations before various effects of selection start to reduce the efficacy of the lineage in restorations (@espeland2017evolution, @pizza2021eight, @conrady2023plants)

@  "Sustainable seed harvesting in wild plant populations" different species can support different amounts of harvest. 
@ theory of how less diversity can harm restorations

#### no species (@wilsey2021restoration) 

(paragraph about difficulty to find/collect)
While most species which are desired in restorations historically have generally had relatively large geographic ranges, numbers of populations, and number of individuals per populations, the development of native germplasm remains behind targets (@national2023assessment). 
We posit that most of these challenges relate to the difficulty in finding populations with the appropriate number of individuals, which are experiencing climatic conditions conducive to producing enough viable seed to being agricultural increase, complications borne of widespread habitat degradation and unnatural wildfires (cite on degradation and wildfires). 
Tools which are capable of predicting a species geographic range, the presence and size of populations across seed collection target units (such as empirical or provisional seed transfer zones or ecoregions), such as Species Distribution Models offer promise to decrease the amount of time spent by field crews scouting populations, whilst increasing their knowledge of the number of populations which are suitable for collection in a single year. 

(paragraph about resolving problems)
However, while SDM's generate hypothesis of whether areas have environmental conditions similar to the observed environmental niche of the species they do not consider the probabilities of colonization, nor the populations census sizes.
A possible tool to associate a probability of occurrence of a species in a suitable habitat patch, is connectivity analysis.
Utilizing the predicted unsuitability of habitat, with extreme barriers to dispersal, to create cost-resistance surfaces between patches with known populations and predicted populations allows for simulating the probability of occurrence. 
While previous correlations between habitat suitability and population size have often been low, we posit that patch level parameters offer a more useful prediction of population size (@weber2017there, @waldock2022quantitative)
Patch metrics will more appropriately reflect parameters of a potential population, e.g. geographic extent, which we posit is a more informative proxy of population size than environmental niche correlation.  

Utilizing this approach will allow field crews to associate probabilities with previously unground truthed patches. 

(paragraph about difficulty to farm seed)
The production of wild harvested seed in agricultural settings whilst preventing natural selection faces multiple challenges... 
Not all farms suitable for all species ... increasing costs of human resources, water, cloth to warm seedlings, and perhaps decreasing yield. 
Within species seed collected closer to harvest sites should do better ... 
(just those two points... )

Goals/Questions/hypotheses.

Here we showcase the utility of SDM's to (1) predict suitable habitat for common species in natural settings and use those data to test two specific hypotheses. Firstly 2) that SDM's can identify more populations than exist in the occurrence based records they were derived from, and secondly 3) patch metrics derived from SDM's correlate with observed population census size. Further we showcase the possibility of SDM's as tools to predict areas which are suitable for agricultural grow-outs to increase seed lot sizes (4).

## old intro 


Drylands constitute roughly ~45% of earths surface (@pruavualie2016drylands). 
These water-limited areas are commonly used as range or pasture lands, hence much of the land is maintained in natural or semi-natural conditions (@reynolds2007globa, @asner2004grazingl). 
Accordingly drylands lands represent an enormous proportion of Earth's remaining natural areas, while fostering roughly 2.5 billion persons, however many of these areas are in ecological states which do not maximize their ecosystem services to either human or wildlife (@reynolds2007global, @bestelmeyer2015desertification).
Historic actions and phenomena such as fire suppression, shrub encroachment, and overgrazing, in combination with climate change and drought are resulting in severe wildfires and their subsequent burns scars which may lead to a regime shifts wherein invasive species dominate burned sites for the foreseeable future (@bestelmeyer2015desertification).
The prevalence of these invasive species decrease the ability of the land to serve multiple ecosystem services, such as to foster both wildlife and pastoral goals, and in extreme cases may preclude uses of the land by both wildlife and humans, and may have require high fiscal costs to return to a more desirable state.

In order to maintain the ecosystem services of burned areas restoration plantings have long been used. 
More recently a focus on utilizing native species, and now locally adapted genotypes, has been adopted as these species and populations have been shown to provide ecosystem services to a variety of wildlife and stakeholders, and they are often more capable of establishing at sites. 
However, the acquisition of native plant materials in the volumes required for restoration, especially in fire prone years, is not yet feasible. 
In an attempt to provide for the demand of locally adapted native plant materials partnerships with farmers who are planting wild harvested seeds, and harvesting their seed for sale to restoration performing agencies has increased. However, the implementation of these goals still face significant challenges.

We anticipate that three particular challenges which are currently being faced in developing and delivering a native seed supply in the Great Basin Ecoregion are ubiquitous to all supply chains. 
1) Locating populations of adequate size that they can have enough viable seed collected from that that it is economically viable for farmers to grow out from the seed lots while not adversely affecting the demographic vital rates of the population. 
2) Minimizing the adverse affects of artificial selection of these seed lines while being increased in agricultural settings. 
3) Ensuring that farmed seeds are applied to the areas in burn scars which they have the highest probability of success. 
We posit that Species Distribution Modelling (SDMs) (or Environmental Niche Modelling (ENM)) may be used as an heuristic to increase the probability of success at each of these stages, and the development of these models are markedly cheaper than purely empirical approaches. 

Locating populations of native species which are large enough to support a seed collection which is large enough to establish an agricultural lot is difficult. 
The areas over which native seed may feasibly be collected in semi-arid areas, which often times have higher proportion of natural areas relative to other settings, are enormous and have generally had their floras coarsely mapped. 
Restoration approaches for sourcing locally adapted seed such as Seed Transfer Zones (STZ's), predictive provincing, or Omernik Level 4 ecoregions, increase the relevancy of identifying many populations suitable for collections across a species range. 
Locating such populations is difficult given the lengths of growing seasons, human resources, and the length of time required to collect enough viable seed. 

Agricultural cultivation presents multiple steps which may alter the frequency of gene forms (alleles) within the seed lots via unintentional artificial selection.
It is theorized that reducing these effects will result in seed lots with a proportion of more individuals with gene forms more typical of the planted wild population, than the offspring derived from it, and hence have more individuals likely to establish in a restoration. 
A method to reduce the demographic bottlenecks associated with recruitment of an individual, and to reduce over-representation of seed from species which are more fit in cultivated settings than the wild may be to reduce the environmental dissimilarity between the wild and cultivated settings. 
These models may also help farmers prioritize which species to grow to have the most successful crops, and to help recruit new farmers to dedicate portions of there fields to developing native plant materials. 

Planning a restoration following a wildfire is a difficult process, due to limitations of both fiscal budget, time, human resources, and knowledge of the heterogeneity of the affected areas. 
Species Distribution Models offer a line of evidence which practitioners may use to identify species which are most suitable for the burned areas in a simple readily query friendly format. 
The utilization of them ...

Herein we develop simple Species Distribution Models, using a variety of predictors which are global in coverage - or for which global analogs exist, and species occurrences from publicly available and rangeland monitoring datasets, to assist in an ongoing effort to develop native plant materials in the Great Basin Ecoregion (U.S.A.). 
Two sets of models are generated for each species, one set which reflects the natural, in particular biophysical the settings of the species, and another set which more closely reflects the climatic envelope and soil properties of the species. 
The former are to assist in challenges of finding populations and restoration efforts while the latter is to support seed increase endeavors.
In attempts to reduce the discrepancies between the fundamental and realized niche, to assist field workers in finding populations, known occurrences are combined with cost-surfaces and predictions of suitability models to provide a consensus surface and emulate the restrictions of dispersal to species distributions. 
Finally, cell statistics are used to create aggregate scores for patches of suitable habitat which have been shown to correlate with abundance. 

