--- 
title: 'Using Species Distribution Models to inform native seed collection efforts' 
author:  |
    |  $^1$Chicago Botanic Garden, 1000 Lake Cook Road, Glencoe, Illinois 60022, USA  
    | Reed Clark Benkendorf$^1$^[Author for Correspondence: rbenkendorf@chicagobotanic.org]
abstract: |
  \noindent
  less than 250 words - no subsections.           
keywords: |
  species distribution models, native seed development  
output:
  pdf_document: default
  toc: no
  word_document: default
csl: "../citations/restoration-ecology.csl"
bibliography: ../citations/bibliography/citations.bib
link-citations: yes
fig_caption: yes
always_allow_html: yes
header-includes:
- \usepackage{endfloat}
- \usepackage{setspace}\doublespacing
- \usepackage{lineno}
- \linenumbers
- \usepackage[width=\textwidth]{caption}
- \usepackage{wrapfig}
- \usepackage[export]{adjustbox}
- \usepackage{rotating} 
--- 

##  IMPLICATIONS FOR PRACTICE

up to six of these. let's shoot 3 with 2 sentence max per. 

```{r echo = F}
knitr::opts_chunk$set(echo=F, warning = F, message = F)
```

# Introduction 

With the United Nations 'Decade of Restoration' well underway limitations in our capacity to carry out active restoration, which normally requires large volumes of seed, are becoming apparent [@national2023assessment]. 
Given the scale of our restoration needs, in most scenarios, the only sustainable source of this quantity of seed are from the amplification ('grow-out') of wild harvested seed in agricultural settings [@pedrini2020collection; @broadhurst2015seeding; @national2023assessment].
Enormous efforts are now underway to increase the number of species, the number of populations within these species, and the genetic diversity of the seed available from agricultural amplification for restoration projects [@national2023assessment, @merritt2011restoration]. 
However, numerous difficulties exist in both the wild harvest of seed and it's subsequent  amplification which are limiting our ability to develop adequate amounts of germplasm.   

While most species desired in restorations have historically had relatively expansive geographic ranges, multitudes of populations - many of which had enormous census sizes, the development of native germplasm remains behind targets [@national2023assessment]. 
We posit that in part this is due to the difficulty of finding populations with the appropriate number of individual plants, which are experiencing climatic conditions conducive to producing enough viable seed which can be sustainably harvested to begin economically feasible agricultural increase.
Essentially the same reasons we need to enact active restoration in the first place,  widespread habitat degradation and unnatural wildfires spurred by climate change and ill-informed historic land management practices, are the same hindrances to developing a locally-adapted and affordable  germplasm  *[@abatzoglou2021projected)]*. 
Heuristic tools which are capable of predicting a species geographic range, the presence of populations across the range, and which can predict them across seed collection target units (e.g. seed transfer zones), such as Species Distribution Models offer promise to increase the rate at which native germplasm can be developed. 

A Species Distribution Model (alternatively referred to as 'Environmental niche models' etc.) uses presence, and optionally absence, records of a species and correlates these records to environmental variables (e.g. climate, land cover, and soil), using various families of statistical models (e.g. GLMs, MaxEnt, decision trees), which allows for the fit model to be predicted onto a gridded (raster) surface. 
While Species Distribution Models (SDMs) only generate hypothesis of whether areas have conditions similar to the observed environmental niche of the species based on the training records these hypothesis are rarely tested, and the link between their predictions and ecological reality have been credibly questioned as being tenuous (@yee). 
In the few published instances where SDMs have been tested, they have oftentimes been for rare species which have rather obvious and consequential drivers of their distributions, e.g. they proliferate on uncommon soils and are outcompeted on more typical soil types. 
Whether the hypotheses generated by these models may be useful for detecting populations or common species, whereby their distributions often appear more governed by more subtle cues, appears unexplored. 
Testing the applicability of SDMs to modeling the range of common species is further valuable as much biodiversity planning incorporates common species which are oftentimes viewed as the fabric holding together ecosystems, and as they may assist with planning restoration plantings under climate change. 

While the goal of an SDM is to develop a testable hypothesis of where a self sustaining population of a species *can* grow, they generally lack an explicit link to estimating *where* a population will actually grow. 
We argue that where populations will occur is driven largely by dispersal limitations, rather than simply whether habitat is suitable. 
A possible tool to associate a probability of occurrence of a species in a suitable habitat patch, is connectivity analysis. 
Connectivity analysis, as generally implemented in land management, often requires a variety of computationally intensive algorithms stemming from a variety of disciplines (e.g. circuit theory).
However we posit that in the case of widespread species useful results can be obtained by simply detailing the occupancy of drainage catchments, and the number of catchments between these occupied sites, and drainages with hypothesized potential habitat.  

In this article we use empirical field verified data to explore two main concepts developed from a large number of SDMs across an expansive geographic range. 
The first is that SDM's are useful for finding populations of species, and that the number of populations found increases with habitat suitability.  
The second is that SDM's are most useful when combined with knowledge of distance from the predicted to the observed cell. 

# 2 MATERIALS AND METHODS  
## 2.1 Study system  

The 353 taxa modeled were selected by land managers working for the Bureau of Land Management in arid & semi-arid areas Western North America and are species they already use, or which they intend to develop for use, in restoration. 
The spatial extent of modelling broadly encompasses the Western United States being bounded by the Pacific Ocean, the 50th parallel at north, -100 degrees at East and Mexico to the south. 
This domain has tremendous variation in amounts of elevation, temperature, and precipitation. 

## Species Occurrence Records  
Species presence records were collected from Natural History Museums, citizen science initiatives, and standardized ecological monitoring programmes using R [@chamberlain2024rgbif; @maitner2023bien; @michonneau2023idigbio]. 
These records were filtered to only those collected after 1950, with coordinate uncertainty less than 250 meters, and only the most recent record per 90m cell was retained. 
All of these records were then manually reviewed by species, where records with more 2 or more variables in the 2.5% quantiles of several environmental variables (bio1, 4, 10, 12, & 19; see TABLE X) and distance were flagged.
During subjective manual review all digitized herbarium specimens which were suspect were reviewed, while other records were dropped based on the analysts review of other occurrence records.   

Species absences were generated using three processes, and we sought to have a 1:1 ratio of presences to absences. 
True absences were acquired from an ecological monitoring program Assess, Inventory, and Monitor (AIM), these absences accounted for a percent equivalent to land managed by BLM within the species range (e.g. if 20% of land ownership across a species range was BLM, than the number of presences * 0.2 defined the number of these absences). 
Likely absences, representing 15% of records, were generated outside the known range of the species, but bounded to be within 50 miles of the extent extent of occurrences. 
Pseudo-absences (PA) were randomly selected from areas in, or within XX km, of the species range but greater than 10km from an occurrence, these records accounted for ((1 - (% BLM Land + 15 % LA records)) * 1.25).
Because most of these species are highly abundant in order to reduce the probability that a PA was drawn within a species the environmental niche linear discriminant analysis (LDA) was used. The LDA utilized the presences, true absences and likely absences as the classes and several environmental variables [@venables2002mass], identified by vifstep with theta = 10 as displaying at most moderate collinearity, as independent variables [@naimi2014usdm]. 
As many records, classified by the LDA as originating from the Presence data set, from the pseudo-absences could be removed as to achieve a class balance between presences and absences. 

## Environmental Variables  
Up to 44 variables were used in generating the species distribution models (Appendix 1). 
These variables were selected based on authors previous work, and represent variables commonly associated with the empirical distributions of taxa in arid and semi-arid regions. 
The thematic contents of these variables largely relate to climate [@karger2017climatologies], landcover [@tuanmu2014global], topography and landform [@amatulli2020geomorpho90m ; @yamazaki2017merit], soil [@hengl2017soilgrids250m; @ivushkin2019global], and representations of anthropogenic impacts [@sanderson2002human]. 
All variables were downloaded from source and re-sampled to 90m resolution using terra [@hijman2024terra]. 

## Species Distribution Modelling  
Random Forests models were generated for each species following several steps to reduce the number of features.
While superfluous features generally do not notably decrease the performance of random forests, they increase the amount of time required to predict models onto gridded surfaces. 
The Boruta algorithm was used on the full stack of 44 independent variables to remove un-informative variables [@kursa2010boruta], and the variable importance factor (VIF) scores were then used to subset the most informative features in several auto-correlated pairs, reducing the independent variables to at most 33.  
Recursive Feature Elimination (rfe) was then used to identify the fewest number of independent variables which could either increase model performance (measured using accuracy), or only decrease it by 1.5% relative to the full set of variables, these variables were subset and used as features for random forest modelling with all default values except for optimized mtrys [@kuhn2008caret; @liaw2002randomForest]. 
Models were then predicted onto raster surfaces which exceeded the species known range by 50 miles [@hijman2024terra]. 

## Patch identification 
To identify putative metapopulations raster cells predicted as having less than 0.8 probability of suitable habitat were masked as NA's, and then areas which were crossed by streams with Strahler orders of three of more [@usgs2004nhd], and the divides of HU10 watersheds [@usgs2023wbd] were 'burnt' away from the raster. 
The resulting rasters were aggregated by a factor of 2 to 5, depending of their sizes (< 300 MiB 2, < 500 MiB 3, < 700 MiB 4, > 700 MiB 5) to accommodate, a rooks case search using terra in a practical time period. 
Resultant patches < 5 acres were then discarded, and the rasters was resampled to it's input resolution.  

Putative populations were identified using the patches generated above. These patches followed the same processing, except that HU12 watersheds were used to delineate populations. 

Because the > 0.8 threshold used above did not capture all colonized patches, all patches with predicted suitability scores of >0.55 which contained species observations were then identified using Terra's patches to create a data set of known populations. 

## Predicting Species Occurrence in Patches

All patches identified above were used to identify patches within 5 contiguous neighbors, or 5 kilometers, of a patch known to be occupied.
Occupied patches were determined using both the training and test occurrences data set used to generate the SDMs. 
To identify each patch within 5 orders of contiguous neighbors `nblag`, and to determine all patches within 5k of a populated patch `dnearneigh`, were used [@bivand2018spdep]. 
For each of these non-occupied patches the number of occupied patches at different lags were counted.  

Each non-occupied patch was assigned an arbitrary rank based upon whether they were contiguous with an occupied patch, and if contiguous than their lag number to the nearest occupied patch, and the number of occupied patches connected (TABLE XX). 
The arbitrarily assigned numbers increase from '1', for an occupied patch, to '7' for a patch which has fewer than 3 second-order contiguous neighbors to an occupied patch(es). 

|  Connection   |  No. Connections   |   Rank   | 
| :-----------: | :----------------: | :------: | 
|     1^st^     |        >= 2        |    2     | 
|     1^st^     |         1          |    3     | 
|     2^nd^     |        >= 3        |    4     | 
|     2^nd^     |        <= 2        |    5     | 
|     3^rd^     |        >= 4        |    6     | 
|     3^rd^     |        <= 3        |    7     | 

Patches which have no contiguous neighbors, but which have neighbors within 5km were also assigned rank values based in this system (TABLE XX). 

|  No. Occupied Patches   |   Rank   | 
| :---------------------: | :------: | 
|           >= 3          |    5     |  
|           <= 2          |    6     | 

# Results 

how many records removed manually?
how many records flagged by LDA?

Which variables were the most important rank positions across all models? 
How were model evaluation statistics?

Where were the populations crews ended up finding? (weird elbow plot)
How did presences and absences interact? (logistic regression)

# Discussion  

# Acknowledgments 

The development of the species distribution models, and the connectivity data products, were funded on a contract awarded to the Chicago Botanic Garden from the Bureau of Land Management.
Ground verification was conducted in the routine operations of 13 contract crews funded by the BLM on the same set of agreements. 
Kristy Snyder is thanked for sharing Seeds of Success field data which were required for the analyses in this manuscript. 
 
# Literature Cited 

# Supporting Information 