---
title: "Predict Models"
author: "steppe"
date: "2024-01-02"
output: html_document
---

```{r}
library(tidyverse)
library(terra)
library(sf)
library(randomForest)
source('functions.R')

setGDALconfig('GDAL_MAX_DATASET_POOL_SIZE=1024')
```

```{r read in predictors}
p <- '~/Documents/WesternPlantPredictors2'
paths <- list.dirs(p, recursive = T)
paths <- paths[2:length(paths)]
paths <- paths[! grepl('chelsa$|veg_cover$|soilgrids$|sand$|silt$|clay$|phh2o$|cfvo$|soc$', paths) ]

files <- lapply(paths, function(x){ file.path(x, list.files(x)) })
names(files) <- basename(paths)

layers <- lapply(files, vrt)
layers <- rast(layers)
names(layers) <- basename(paths)

rm(paths, files)
```

```{r read in models}

targets <- read.csv('../data/raw/2024sos_species.csv', na.strings = "") %>% 
  
  ## we will not model a few species which are widely abundant, hence do not require modelling, and would utilize enormous computational resources.
  filter(!species %in% c('tridentata', 'millefolium', 'dioica', 'negundo')) %>%  # purshia,
  unite('taxon', genus:infraspecies, na.rm = T, sep = ' ') %>% # artemisia, and larrea !
  mutate(taxon = str_squish(taxon))

target_taxa <- c('Brodiaea elegans', 'Krameria bicolor', 'Lotus humistratus', 'Adenostoma fasciculatum')

## these species missed, fixed on March 13th
target_taxa <- read.csv('../data/raw/2024sos_species-FIXED.csv', na.strings = "") %>% 
  filter(!species %in% c('tridentata', 'millefolium', 'dioica', 'negundo')) %>%  # purshia,
  unite('taxon', genus:infraspecies, na.rm = T, sep = ' ') %>% # artemisia, and larrea !
  mutate(taxon = str_squish(taxon)) %>% 
  filter(! taxon %in% c(targets$taxon, target_taxa)) %>% 
  pull(taxon)

pmodels <- '../results/rf_models'
f <- file.path(pmodels, list.files(pmodels))
files <- f[grep(paste(paste0(gsub(' ', '_', target_taxa)), collapse = '|'), basename(f))]

rm(target_taxa)

occpath <- '../data/raw/occurrence/combined_records'

occ_files <- paste0( basename(gsub('1k.*', '', files)), '.shp')

models_occ <- data.frame(
  path2model = files, occurrence_data = occ_files
) %>% 
  mutate(
    species = gsub('-.*$', '', basename(path2model)),
    match = if_else(species == gsub('[.]shp$', '', occurrence_data), T, F )
  ) # all look good!

models_occ <- split(models_occ, f = models_occ$species)

predict_wrapper <- function(x){
  
  sdm <- readRDS(x$path2model)
  occ_path <- file.path(occpath, x$occurrence_data)
  
  # read in occurrences and subset prediction to 100 miles from border
  bound <- sf::st_read(occ_path, quiet = TRUE) |>
    dplyr::filter(Occurrence == 1) |>
    sf::st_union() |>
    sf::st_convex_hull() |>
    sf::st_buffer(80467) |>
    sf::st_bbox()
  
  pout <- '~/Documents/suitability_maps'
  layer_subset <- terra::subset(layers, term_grab(sdm))
  layer_subset <- terra::crop(layer_subset, bound)
  
  OneClass <- \(...) predict(...)[,2]
  terra::predict(
    layer_subset, sdm, cpkgs="randomForest",
    type = 'prob', cores = 1, f = OneClass,
    filename = file.path(pout, paste0(x$species, '-', gsub(' ', '_', Sys.time()), '.tif')),
    wopt = c(names = 'predicted_suitability'))
  
   terra::tmpFiles(current = FALSE, orphan = TRUE, old = TRUE, remove = TRUE)
  
}

lapply(models_occ, predict_wrapper)
```




```{r predict second set of models}

targets <- read.csv('../data/raw/2024sos_species.csv', na.strings = "") %>% 
  
  ## we will not model a few species which are widely abundant, hence do not require modelling, and would utilize enormous computational resources.
  filter(!species %in% c('tridentata', 'millefolium', 'dioica', 'negundo')) %>%  # purshia,
  unite('taxon', genus:infraspecies, na.rm = T, sep = ' ') %>% # artemisia, and larrea !
  mutate(taxon = str_squish(taxon))

target_taxa <- c('Brodiaea elegans', 'Krameria bicolor', 'Lotus humistratus', 'Adenostoma fasciculatum')

## these species missed, fixed on March 13th
target_taxa <- read.csv('../data/raw/2024sos_species-FIXED.csv', na.strings = "") %>% 
  filter(!species %in% c('tridentata', 'millefolium', 'dioica', 'negundo')) %>%  # purshia,
  unite('taxon', genus:infraspecies, na.rm = T, sep = ' ') %>% # artemisia, and larrea !
  mutate(taxon = str_squish(taxon)) %>% 
  filter(! taxon %in% c(targets$taxon, target_taxa)) %>% 
  pull(taxon)

pmodels <- '../results/rf_models'
f <- file.path(pmodels, list.files(pmodels))
files <- f[grep(paste(paste0(gsub(' ', '_', target_taxa)), collapse = '|'), basename(f))]

rm(target_taxa)

occpath <- '../data/raw/occurrence/combined_records'

occ_files <- paste0( basename(gsub('1k.*', '', files)), '.shp')

models_occ <- data.frame(
  path2model = files, occurrence_data = occ_files
) %>% 
  mutate(
    species = gsub('-.*$', '', basename(path2model)),
    match = if_else(species == gsub('[.]shp$', '', occurrence_data), T, F )
  ) # all look good!

models_occ <- split(models_occ, f = models_occ$species)

predict_wrapper <- function(x){
  
  sdm <- readRDS(x$path2model)
  occ_path <- file.path(occpath, x$occurrence_data)
  
  # read in occurrences and subset prediction to 100 miles from border
  bound <- sf::st_read(occ_path, quiet = TRUE) |>
    dplyr::filter(Occurrence == 1) |>
    sf::st_union() |>
    sf::st_convex_hull() |>
    sf::st_buffer(80467) |>
    sf::st_bbox()
  
  pout <- '~/Documents/suitability_maps'
  layer_subset <- terra::subset(layers, term_grab(sdm))
  layer_subset <- terra::crop(layer_subset, bound)
  
  OneClass <- \(...) predict(...)[,2]
  terra::predict(
    layer_subset, sdm, cpkgs="randomForest",
    type = 'prob', cores = 1, f = OneClass,
    filename = file.path(pout, paste0(x$species, '-', gsub(' ', '_', Sys.time()), '.tif')),
    wopt = c(names = 'predicted_suitability'))
  
   terra::tmpFiles(current = FALSE, orphan = TRUE, old = TRUE, remove = TRUE)
  
}

lapply(models_occ, predict_wrapper)
```

