---
title: "Download data"
author: "steppe"
date: "2023-10-14"
output: html_document
---

```{r load packages}
library(tidyverse)
library(terra)
library(sf)
source('functions.R')
```

Identify what areas crews require data for. 

```{r Crew Info}

blm <- st_read( quiet = T,
  '/media/steppe/hdd/Geospatial_data/Public_land_ownership/BLM_West_simplified/BLM_West_simplified.shp') %>% 
  st_transform(5070)

crew_locs <- read.csv('../data/raw/crew_locations.csv') %>% 
  mutate(across(.cols = everything(), ~ na_if(., ''))) %>% 
  pivot_longer(cols = FO1:FO5, names_to = 'FO', values_to = 'FieldOffice' ) %>% 
  drop_na() %>% 
  select(-FO)

teams <- filter(crew_locs, !str_detect(Contract, 'Senior')) %>% 
  mutate(FieldOffice = paste(FieldOffice, 'Field Office')) 

seniors <- filter(crew_locs, str_detect(Contract, 'Senior')) %>% 
  rename(Senior = Contract, Contract = FieldOffice) %>% 
  left_join(., teams, by = 'Contract')

blm <- filter(blm, Unit_Nm %in% seniors$FieldOffice)

rm(crew_locs)
```


```{r jitter the AIM data, eval = F}
set.seed(125)
occ_p <- '/media/steppe/hdd/SDM_restorations/data/raw/occurrence/combined_records'
occurrences <- lapply(
  file.path(occ_p, list.files(occ_p, pattern = 'shp$')), st_read, quiet = T) |>
  bind_rows() %>% 
  filter(Occurrence == 1) %>% 
  select(taxon, date, PtType)
occ_aim <- filter(occurrences, PtType == 'AIM Presence') %>% 
  st_jitter(amount = 250)
occurrences <- bind_rows(
  filter(occurrences, PtType != 'AIM Presence'), 
  occ_aim) %>% 
  mutate(
    PtType = if_else(PtType == 'AIM Presence', 'jittered', 'exact'),
    date = as.numeric(str_extract(date, '[0-9]{4}'))
    ) %>% 
  rename(year = date, coord_status = PtType) %>% 
  arrange(taxon, year, coord_status)

st_write(occurrences, file.path(occ_p, 'jittered_occurrences.shp'), quiet = T, append = F)

rm(occ_p, occ_aim)
```

Identify which species crews require. 

```{r}

spp_needed <- read.csv('../data/raw/2024sos_species-FIXED.csv') %>% 
  unite('binomial', genus:species) %>% 
  select(binomial, contract) %>% 
  mutate(binomial = str_trim(binomial))

spp_needed <- read.csv('../data/raw/contract_lkp.csv') %>% 
  left_join(spp_needed, ., by = c('contract' = 'Contract_colloquial')) %>% 
  select(-contract) %>% 
  distinct()
```

```{r import data}

p <- '/media/steppe/hdd/Geospatial_data/'

blm_surf <- st_read(paste0(p, 'Public_land_ownership/BLM_West_simplified/BLM_West_simplified.shp'), quiet = TRUE)
usfs_surf <- st_read(paste0(p, 'Public_land_ownership/USFS_West_simplified/USFS_West_simplified.shp'), quiet = TRUE)
invasives <- rast(paste0(p, 'MRLC/', '2023_InvGrassCover.tif'))
change_intensity <- rast(paste0(p, 'MRLC/total_change_intensity_index/', 'TCII_3arc.tif'))
fire_perimeters <- st_read( quiet = T,
  paste0(p, 'NIFC_perimeters/', 'InterAgencyFirePerimeterHistory_All_Years_View-Simplified.shp'))
SWSTZ <- st_read( quiet = T,
  paste0(p, 'provisional_SeedTransferZones/', 'desertSW/desert_southwest_provisional_seed_transfer_zones_USGS.shp')) %>% 
  select(seed_zone = Zone) %>% 
  mutate(Dataset = 'SWSTZ', .before = geometry, seed_zone = as.character(seed_zone))
BOWERSTZ <- st_read( quiet = T,
  paste0(p, 'provisional_SeedTransferZones/', 'WWETAC_STZ/GB_2013_revised_reduced.shp')) %>% 
  select(seed_zone) %>% 
  mutate(Dataset = 'BowerRevised', .before = geometry)
STZ <- bind_rows(BOWERSTZ, SWSTZ) %>% 
  st_transform(5070)
roads <- st_read(quiet = T, paste0(p, 'blmRoadsSOS24/processed/BLM_roads.shp'))
admin_boundaries <- st_read(paste0(p, 'Public_land_ownership/BLM_ADMU/BLM_ADMU_BOUNDARIES.shp'), quiet = TRUE)
allotments <- st_read(
  file.path(p, 'Public_land_ownership/BLM_Natl_Grazing_Allotment_Polygons/Allotment-simp.shp'), quiet = T) %>% 
  select(ALLOT_NAME)

occ_p <- '/media/steppe/hdd/SDM_restorations/data/raw/occurrence/jittered_occurrences'
occurrences <- st_read(file.path(occ_p, 'jittered_occurrences.shp'), quiet = T)

rm(SWSTZ, BOWERSTZ, occ_p)
```

```{r}
teams_list <- split(teams, f = teams$Contract)
```

```{r generate projects for crews, eval= F}

lapply(teams_list, project_maker,
       admu = admin_boundaries, 
       target_species = spp_needed, 
       blm_surf = blm_surf, 
       fs_surf = usfs_surf, 
       fire = fire_perimeters, 
       invasive = invasives, 
       total_change = change_intensity, 
       occurrences = occurrences, 
      # historic_SOS, 
       roads = roads, seed_transfer = STZ)

ob <- st_read('/media/steppe/hdd/2024SOS_CrewGeospatial/Eastern Mojave - P102073/Geodata/Species/SDM/Salazaria_mexicana.shp')

```

Now we can generate estimates of flowering duration in certain field offices

```{r generate phenology spreadsheet for crews}

spp_needed <- rename(spp_needed, taxon = binomial)

p2ts <- '/media/steppe/hdd/SeedPhenology/data/processed/timestamps'
lapply(
  X = teams_list, 
  FUN = phen_tabulator,
  path = p2ts, 
  admu = admin_boundaries, 
  target_species = spp_needed
  )


```

